### ISSUE TITLE
Is this project updated?

### ISSUE THREAD

**Issue by robsonpeixoto** [tillrohrmann/flink-project#5]
This template can be used on new Flink version?
Then maven version has a lot of `maven-shade-plugin` configuration, why is it not necessary on sbt version?

Thanks for this great template =D

**Comment by tillrohrmann** [comment]
Hi @robsonpeixoto. The repo hasn't been kept up to date with the Flink project since it points still to Flink 1.7.0. In general there shouldn't be a problem updating it to the latest Flink version. What might have changed a bit are which dependencies need to be pulled in.

The reason why we don't need the shading configuration is that SBT's assembly plugin takes care of creating a fat jar.
